from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
from datetime import datetime  # noqa: F401


@runtime_checkable
class IStorage(Protocol):
    async def save_company(self, company: Any) -> None: ...
    async def get_company(self, company_id: str) -> Any | None: ...
    async def save_agent(self, agent: Any) -> None: ...
    async def get_agent(self, agent_id: str) -> Any | None: ...
    async def list_agents(self, company_id: str) -> list[Any]: ...
    async def save_message(self, message: Any) -> None: ...
    async def get_messages(self, company_id: str, agent_id: str) -> list[Any]: ...
    async def claim_pending_inbox(self, company_id: str, agent_id: str) -> list[Any]: ...
    async def save_audit(self, entry: Any) -> None: ...
    async def save_checkpoint(self, cp: Any) -> None: ...
    async def get_checkpoints(self, company_id: str) -> list[Any]: ...
    async def update_checkpoint_status(
        self, company_id: str, step_index: int, status: str,
        output: str | None, error: str | None, cost_usd: float,
    ) -> None: ...
    async def delete_checkpoints(self, company_id: str) -> None: ...


@runtime_checkable
class ILLM(Protocol):
    async def ask(
        self, *, system_prompt: str, user_prompt: str, model: str,
        allowed_tools: list[str], max_turns: int, output_schema: dict | None,
        **kwargs: Any,
    ) -> Any: ...


@runtime_checkable
class IWorker(Protocol):
    async def execute(
        self, instruction: str, *, output_schema: dict | None,
        inbox: list[Any], peer_roles: list[str], **kwargs: Any,
    ) -> Any: ...


@runtime_checkable
class ICEO(Protocol):
    async def plan(self, _clarifications: str | None = None) -> Any: ...
    async def orchestrate(self, plan: Any) -> str: ...


@runtime_checkable
class ISecurityHooks(Protocol):
    def pre_bash_guard(self, command: str, role: str | None = None) -> None: ...
    def pre_tool_guard(self, tool_name: str, role: str | None = None) -> None: ...
    def get_effective_bash_patterns(self, role: str | None = None) -> list[str]: ...
